# Generated by Django 5.2.7 on 2026-09-22 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DubbingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500)),
                ('video_id', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('uploader', models.CharField(blank=True, max_length=200)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('source_language', models.CharField(blank=True, choices=[('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('te', 'Telugu'), ('bn', 'Bengali'), ('gu', 'Gujarati'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('pa', 'Punjabi'), ('ur', 'Urdu'), ('de', 'German'), ('fr', 'French'), ('es', 'Spanish'), ('it', 'Italian'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('ru', 'Russian'), ('tr', 'Turkish'), ('ar', 'Arabic'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese')], max_length=10)),
                ('detected_language', models.CharField(blank=True, max_length=10)),
                ('diarize', models.BooleanField(default=True)),
                ('clone_voices', models.BooleanField(default=True)),
                ('min_speakers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_speakers', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('download', 'Downloading video'), ('extract_audio', 'Extracting audio'), ('transcribe', 'Transcribing speech'), ('diarize', 'Identifying speakers'), ('translate', 'Translating'), ('synthesize', 'Synthesising English speech'), ('mix', 'Mixing and muxing')], default='pending', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('source_video', models.FileField(blank=True, max_length=500, upload_to='')),
                ('speech_audio', models.FileField(blank=True, max_length=500, upload_to='')),
                ('output_video', models.FileField(blank=True, max_length=500, upload_to='')),
                ('stage_timings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dubbing_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dubbing_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='dubbing_job_queue_idx')],
            },
        ),
    ]
