# Generated by Django 5.2.7 on 2026-09-22 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbingjob',
            name='asr_model',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='dubbingjob',
            name='language_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dubbingjob',
            name='transcribed_until',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dubbingjob',
            name='word_aligned',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('text', models.TextField()),
                ('words', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.dubbingjob')),
            ],
            options={
                'db_table': 'dubbing_segments',
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('job', 'index'), name='unique_segment_index_per_job')],
            },
        ),
    ]
