# Generated by Django 5.2.7 on 2026-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='dubbingjob',
            name='translation_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='segment',
            name='translated_text',
            field=models.TextField(blank=True),
        ),
    ]
