# Generated by Django 5.2.7 on 2026-09-08 12:31

import EduEssence.backend.Classroom.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('join_code', models.CharField(default=EduEssence.backend.Classroom.models.generate_join_code, max_length=6, unique=True)),
                ('room_name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Live classes',
                'db_table': 'live_classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassUtterance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('original_text', models.TextField()),
                ('source_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('stt_provider', models.CharField(blank=True, max_length=30)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utterances', to='classroom.liveclass')),
            ],
            options={
                'db_table': 'class_utterances',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ClassParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_participations', to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='classroom.liveclass')),
            ],
            options={
                'db_table': 'class_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='UtteranceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('translated_text', models.TextField()),
                ('audio_base64', models.TextField(blank=True)),
                ('audio_format', models.CharField(blank=True, max_length=30)),
                ('translation_provider', models.CharField(blank=True, max_length=30)),
                ('tts_provider', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='classroom.classutterance')),
            ],
            options={
                'db_table': 'utterance_translations',
                'ordering': ['target_language'],
            },
        ),
        migrations.AddConstraint(
            model_name='classutterance',
            constraint=models.UniqueConstraint(fields=('live_class', 'sequence'), name='unique_utterance_sequence_per_class'),
        ),
        migrations.AddConstraint(
            model_name='classparticipant',
            constraint=models.UniqueConstraint(fields=('live_class', 'student'), name='unique_participant_per_class'),
        ),
        migrations.AddConstraint(
            model_name='utterancetranslation',
            constraint=models.UniqueConstraint(fields=('utterance', 'target_language'), name='unique_translation_per_language'),
        ),
    ]
