"""
Django settings for EduEssence project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

for _env_file in (BASE_DIR / '.env', BASE_DIR.parent / '.env'):
    if _env_file.exists():
        load_dotenv(_env_file)
        break


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-wt8_4(34hvu0(d3@47j80p1@nyck=22l&jk4y33q$#et0*72k1',
)

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ENV_LIST_NOISE = '[]\'" '


def _split_env(name, default=''):
    raw = os.environ.get(name, default).strip().strip(ENV_LIST_NOISE)
    items = [item.strip(ENV_LIST_NOISE) for item in raw.split(',')]
    return [item for item in items if item]


def _as_host(value):
    return value.split('//')[-1].split('/')[0].split(':')[0]


def _as_origin(value):
    return value.rstrip('/')


ALLOWED_HOSTS = [_as_host(host) for host in _split_env('ALLOWED_HOSTS', 'localhost,127.0.0.1')]

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if '.' in host]

CORS_ALLOWED_ORIGINS = [_as_origin(origin) for origin in _split_env('CORS_ALLOWED_ORIGINS')]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'Auth',
    'Translation',
    'Classroom',
    'videos',
]

AUTH_USER_MODEL = 'user_auth.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'SIGNING_KEY': SECRET_KEY,
}

GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
GROQ_STT_MODEL = os.environ.get('GROQ_STT_MODEL', 'whisper-large-v3-turbo')
GROQ_TRANSLATION_MODEL = os.environ.get('GROQ_TRANSLATION_MODEL', 'qwen/qwen3.8-27b')

SARVAM_API_KEY = os.environ.get('SARVAM_API_KEY', '')
SARVAM_STT_MODEL = os.environ.get('SARVAM_STT_MODEL', 'saarika:v2')
SARVAM_TRANSLATION_MODEL = os.environ.get('SARVAM_TRANSLATION_MODEL', 'mayura:v1')
SARVAM_TTS_MODEL = os.environ.get('SARVAM_TTS_MODEL', 'bulbul:v2')
SARVAM_TTS_SPEAKER = os.environ.get('SARVAM_TTS_SPEAKER', 'anushka')

STT_PROVIDER = os.environ.get('STT_PROVIDER', 'groq')
TRANSLATION_PROVIDER = os.environ.get('TRANSLATION_PROVIDER', 'groq')
TTS_PROVIDER = os.environ.get('TTS_PROVIDER', 'google')

LIVEKIT_URL = os.environ.get('LIVEKIT_URL', '')
LIVEKIT_API_KEY = os.environ.get('LIVEKIT_API_KEY', '')
LIVEKIT_API_SECRET = os.environ.get('LIVEKIT_API_SECRET', '')
LIVEKIT_TOKEN_TTL = int(os.environ.get('LIVEKIT_TOKEN_TTL', '21600'))

CLASS_STREAM_PAGE_SIZE = int(os.environ.get('CLASS_STREAM_PAGE_SIZE', '20'))

FFMPEG_BINARY = os.environ.get('FFMPEG_BINARY', 'ffmpeg')
FFPROBE_BINARY = os.environ.get('FFPROBE_BINARY', 'ffprobe')
DUBBING_MAX_VIDEO_HEIGHT = int(os.environ.get('DUBBING_MAX_VIDEO_HEIGHT', '1080'))
DUBBING_MAX_DURATION_SECONDS = int(os.environ.get('DUBBING_MAX_DURATION_SECONDS', str(3 * 60 * 60)))
DUBBING_WORKER_POLL_SECONDS = float(os.environ.get('DUBBING_WORKER_POLL_SECONDS', '5'))
DUBBING_PROGRESS_INTERVAL_SECONDS = float(os.environ.get('DUBBING_PROGRESS_INTERVAL_SECONDS', '2'))
DUBBING_DEVICE = os.environ.get('DUBBING_DEVICE', 'auto')
DUBBING_KEEP_MODELS_LOADED = os.environ.get('DUBBING_KEEP_MODELS_LOADED', 'False') == 'True'
DUBBING_WHISPER_MODEL = os.environ.get('DUBBING_WHISPER_MODEL', 'large-v3')
DUBBING_WHISPER_COMPUTE_TYPE = os.environ.get('DUBBING_WHISPER_COMPUTE_TYPE', '')
DUBBING_WHISPER_BATCH_SIZE = int(os.environ.get('DUBBING_WHISPER_BATCH_SIZE', '16'))
DUBBING_TRANSCRIBE_WINDOW_SECONDS = int(os.environ.get('DUBBING_TRANSCRIBE_WINDOW_SECONDS', '600'))
DUBBING_MAX_SEGMENT_SECONDS = float(os.environ.get('DUBBING_MAX_SEGMENT_SECONDS', '12'))
DUBBING_MIN_SEGMENT_SECONDS = float(os.environ.get('DUBBING_MIN_SEGMENT_SECONDS', '1'))
DUBBING_ASR_PROVIDER = os.environ.get('DUBBING_ASR_PROVIDER', 'whisperx')
DUBBING_GROQ_ASR_MODEL = os.environ.get('DUBBING_GROQ_ASR_MODEL', 'whisper-large-v3')
DUBBING_GROQ_TIMEOUT = int(os.environ.get('DUBBING_GROQ_TIMEOUT', '180'))

HF_TOKEN = os.environ.get('HF_TOKEN', '')
DUBBING_INDICTRANS2_MODEL = os.environ.get('DUBBING_INDICTRANS2_MODEL', 'ai4bharat/indictrans2-indic-en-1B')
DUBBING_NLLB_MODEL = os.environ.get('DUBBING_NLLB_MODEL', 'facebook/nllb-200-3.3B')
DUBBING_TRANSLATION_BATCH_SIZE = int(os.environ.get('DUBBING_TRANSLATION_BATCH_SIZE', '8'))
DUBBING_TRANSLATION_BEAMS = int(os.environ.get('DUBBING_TRANSLATION_BEAMS', '5'))
DUBBING_TRANSLATION_CANDIDATES = int(os.environ.get('DUBBING_TRANSLATION_CANDIDATES', '4'))
DUBBING_TRANSLATION_SCORE_TOLERANCE = float(os.environ.get('DUBBING_TRANSLATION_SCORE_TOLERANCE', '0.1'))
DUBBING_ENGLISH_CHARS_PER_SECOND = float(os.environ.get('DUBBING_ENGLISH_CHARS_PER_SECOND', '15'))

PROVIDER_TIMEOUT = int(os.environ.get('PROVIDER_TIMEOUT', '20'))
MAX_UTTERANCE_BYTES = int(os.environ.get('MAX_UTTERANCE_BYTES', str(6 * 1024 * 1024)))

DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UTTERANCE_BYTES + (1024 * 1024)
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

SPECTACULAR_SETTINGS = {
    'TITLE': 'EduEssence API',
    'DESCRIPTION': 'REST API for the EduEssence platform.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SORT_OPERATIONS': False,
    'ENUM_NAME_OVERRIDES': {
        'LanguageEnum': 'Translation.languages.LANGUAGE_CHOICES',
        'SessionStatusEnum': 'Translation.models.SESSION_STATUS_CHOICES',
        'SessionModeEnum': 'Translation.models.SESSION_MODE_CHOICES',
        'ClassStatusEnum': 'Classroom.models.CLASS_STATUS_CHOICES',
        'DubbingJobStatusEnum': 'videos.models.JOB_STATUS_CHOICES',
        'DubbingJobStageEnum': 'videos.models.JOB_STAGE_CHOICES',
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EduEssence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EduEssence.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}

DATABASES['default']['CONN_HEALTH_CHECKS'] = True

# The dubbing worker writes progress while the API reads it. On SQLite that
# means two processes on one file, so wait for the lock instead of failing.
if DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    DATABASES['default'].setdefault('OPTIONS', {})['timeout'] = 20


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
