# Generated by Django 5.2.7 on 2026-09-08 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('source_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('mode', models.CharField(choices=[('in_person', 'In person'), ('online', 'Online')], default='in_person', max_length=20)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teaching_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('source_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('bn', 'Bengali'), ('ta', 'Tamil'), ('te', 'Telugu'), ('kn', 'Kannada'), ('gu', 'Gujarati')], max_length=10)),
                ('stt_provider', models.CharField(blank=True, max_length=30)),
                ('translation_provider', models.CharField(blank=True, max_length=30)),
                ('tts_provider', models.CharField(blank=True, max_length=30)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='translation.teachingsession')),
            ],
            options={
                'db_table': 'transcript_chunks',
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='unique_chunk_sequence_per_session')],
            },
        ),
    ]
